<?php

/**
 *
 * @file
 * Primary module hooks for stripe by habeuk module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
function stripebyhabeuk_library_info_alter(&$libraries, $extension) {
  // \Drupal::messenger()->addMessage('stripebyhabeuk_library_info_alter');
}

function stripebyhabeuk_page_attachments(array &$attachments) {
  // \Drupal::messenger()->addMessage('stripebyhabeuk_page_attachments');
}

function stripebyhabeuk_page_attachments_alter(array &$attachments) {
  // \Drupal::messenger()->addMessage('stripebyhabeuk_page_attachments_alter');
}

/**
 * implement hook_commerce_checkout_pane_info_alter
 * ( cela permet de remplacer les classes par defaut ).
 */
function stripebyhabeuk_commerce_checkout_pane_info_alter(&$definitions) {
  if (!empty($definitions['payment_information']['class'])) {
    $definitions['payment_information']['class'] = "Drupal\stripebyhabeuk\Handler\StripebyHabeukPaymentInformation";
  }
}

/**
 * implement hook_ENTITY_TYPE_load
 */
function stripebyhabeuk_commerce_payment_gateway_load($entities) {
  foreach ($entities as $entity) {
    /**
     *
     * @var \Drupal\commerce_payment\Entity\PaymentGateway $entity
     */
    /**
     * Permet de modifier le display name pour les commerce_payment_gateway
     * utilisant le plugin stripebyhabeuk_acompte.
     */
    if ($entity->getPluginId() == "stripebyhabeuk_acompte") {
      // \Drupal::messenger()->addStatus('label : ' . $entity->label());
    }
  }
}



